html = """
<!DOCTYPE html>
<html>
<head>
    <title>AI Startup</title>
    <style>
        body{
            background:#0f172a;
            color:white;
            font-family:Arial;
            text-align:center;
            padding-top:100px;
        }

        h1{
            font-size:50px;
        }

        p{
            color:#cbd5e1;
        }

        button{
            padding:15px 30px;
            border:none;
            border-radius:10px;
            background:#3b82f6;
            color:white;
            font-size:18px;
        }
    </style>
</head>
<body>

<h1>AI Startup Platform</h1>
<p>Landing page generated by AI engineer workflow.</p>

<button>Get Started</button>

</body>
</html>
"""

with open("index.html", "w", encoding="utf-8") as f:
    f.write(html)

print("Website berhasil dibuat.")